# NOTE: this file was generated by the Mobile NixOS installer.
{ lib, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8cbb77f4-24f7-4c9c-9ea4-23d4236cb64c";
      fsType = "btrfs";
      options = [ "noatime" "nodiratime" "compress=zstd:3" ];
    };
  };

  boot.initrd.luks.devices = {
    "rootfs-luks" = {
      device = "/dev/disk/by-uuid/392a887a-9bb9-4fd1-af9d-05b725c4594e";
      allowDiscards = true;
    };
  };

  nix.settings.max-jobs = lib.mkDefault 2;
}
