# NOTE: this file was generated by the Mobile NixOS installer.
{ lib, ... }:

{
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8d0e44d4-e9b8-4b25-8772-443cd6267b3f";
      fsType = "btrfs";
      options = [
        "compress=zstd"
        "ssd_spread"
        "discard=async"
        "noatime"
        "autodefrag"
        "commit=60"
      ];
    };
  };

  boot.initrd.luks.devices = {
    "LUKS-PINEPHONE-PRO-ROOTFS" = {
      device = "/dev/disk/by-uuid/052d3146-be67-4cb5-89bd-49d2def2501c";
      allowDiscards = true;
    };
  };

  nix.settings.max-jobs = lib.mkDefault 3;
}
